// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE1CUFKOZ4yH_O-coTI2we8zxTnZ_1oPM',
    appId: '1:152726212530:web:2045b0d68a5faae3051eab',
    messagingSenderId: '152726212530',
    projectId: 'feed-bee',
    authDomain: 'feed-bee.firebaseapp.com',
    storageBucket: 'feed-bee.firebasestorage.app',
    measurementId: 'G-DE50VKSP74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8xuDfYCbu3eB0vfF6HiqqIKgmYRnyIqM',
    appId: '1:152726212530:android:9c318d08593224b4051eab',
    messagingSenderId: '152726212530',
    projectId: 'feed-bee',
    storageBucket: 'feed-bee.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_J_EiLtZ7iStbtiTeOP60WigVShO0wWU',
    appId: '1:152726212530:ios:3ce08f2719c873bd051eab',
    messagingSenderId: '152726212530',
    projectId: 'feed-bee',
    storageBucket: 'feed-bee.firebasestorage.app',
    iosBundleId: 'com.example.feedbee',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_J_EiLtZ7iStbtiTeOP60WigVShO0wWU',
    appId: '1:152726212530:ios:3ce08f2719c873bd051eab',
    messagingSenderId: '152726212530',
    projectId: 'feed-bee',
    storageBucket: 'feed-bee.firebasestorage.app',
    iosBundleId: 'com.example.feedbee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE1CUFKOZ4yH_O-coTI2we8zxTnZ_1oPM',
    appId: '1:152726212530:web:478768d86272e0a4051eab',
    messagingSenderId: '152726212530',
    projectId: 'feed-bee',
    authDomain: 'feed-bee.firebaseapp.com',
    storageBucket: 'feed-bee.firebasestorage.app',
    measurementId: 'G-XEMVKP5Y3D',
  );
}
